**Feature Engineering**

- so far we have performed feature analysis
  - Dataframe quick check
  - Catagorical column analysis
  - Bar chart, Pie Chart
  - Numerical column analysis
  - Histogram, Box plot,Outlier
  - Bi-multi variate analysis
  - correlation etc
- Now we learn to feature Engineering 
  - we will create a new columns for better MLmodels
  - we will perform the **Encoding**,which is convert catagorical to numerical data
  - we will do data **transformation**
  - we will perform **Scalling:Standardization and Normalization**
  - we will perform the **missing value analysis**
-simply feature engineering mass our data will be notified

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
visa_df=pd.read_csv(r'C:\Users\HP\Documents\Data_File\Visadataset.csv')
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [3]:
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [6]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

**case_status**

In [5]:
# how many unique labels
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [6]:
# create a mapper
d={'Certified':0,'Denied':1}

In [8]:
#overwrite in same column
visa_df['case_status']=visa_df['case_status'].map(d)
visa_df['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [9]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [11]:
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [44]:
labels=sorted(visa_df['continent'].unique())
d={}
for i,j in enumerate(labels):
    d[j]=i
print(d)

{'Africa': 0, 'Asia': 1, 'Europe': 2, 'North America': 3, 'Oceania': 4, 'South America': 5}

In [45]:
visa_df['continent']=visa_df['continent'].map(d)
visa_df['continent']

0        1
1        1
2        1
3        1
4        0
        ..
25475    1
25476    1
25477    1
25478    1
25479    1
Name: continent, Length: 25480, dtype: int64

In [46]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [47]:
labels=sorted(visa_df['continent'].unique())
d={i:j for i,j in enumerate(labels)}
visa_df['continent']=visa_df['continent'].map(d)
visa_df['continent']
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [48]:
visa_df=pd.read_csv(r'C:\Users\HP\Documents\Data_File\Visadataset.csv')
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

for col in cat[1:]: 
    labels=sorted(visa_df[col].unique())
    d={j:i for i,j in enumerate(labels)}
    visa_df[col]=visa_df[col].map(d)

In [49]:
visa_df[col]

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [50]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [51]:
wine_df=pd.read_csv(r'C:\Users\HP\Documents\Data_File\winequality_red.csv')
wine_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

**Encoding**

- we create a dictionary, we map to original data

- overwrite innthe same column

- the same we can develope by using sckiti learn library

- installati on name:**Scikit learn**
    
- import name: **sklearn**

  - library:**Sklearn**
              
    - modules:**preprocessing**

        - class:**LabelEncoder**
              
          - method:**fit_transform**
              
-

In [1]:
import sklearn
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform

In [2]:
sklearn

In [ ]:
# import the class 
# save the class
#apply the fit transform

**Fit VS Fit_transform**

- if we are finding somrthing then go for **fit**

- if we are finding some new value and using those values to modify the data then go for:       **fit_transform**

- we first develope the dictionary:**fit**

- we used the dictionary and change the data cat to num:**transform**

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
visa_df=pd.read_csv(r'C:\Users\HP\Documents\Data_File\Visadataset.csv')
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [29]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0], shape=(25480,))

In [30]:
visa_df['case_status']=le.fit_transform(visa_df['case_status'])

In [31]:
visa_df['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [10]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['continent'])
visa_df['continent']=le.fit_transform(visa_df['continent'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [16]:

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    le.fit_transform(visa_df[i])
    visa_df[i]=le.fit_transform(visa_df[i])

In [17]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**Explore about inverse transform**

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
visa_df=pd.read_csv(r'C:\Users\HP\Documents\Data_File\Visadataset.csv')
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [6]:
data=le.fit_transform(visa_df['education_of_employee'])

In [7]:
data[:5]

array([2, 3, 0, 0, 3])

In [8]:
le.inverse_transform(data)[:5]

array(['High School', "Master's", "Bachelor's", "Bachelor's", "Master's"],
      dtype=object)

In [9]:
visa_df['education_of_employee'].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [ ]:
'High School':2
"Master's":3
"Bachelor's":0
'Doctorate':1
################################################
# ordinal data
# 'High School'<"Master's"<"Bachelor's"< 'Doctorate'
####################################################
# nominal data
# ramesh  suresh  satish  mahesh  anish  akash

- LabelEncoder use only for**Nominal level data**
                        
- 90% target columns use only **LabelEncoder**

- for ordinal level data will go for OrdinalEncoder

- sklearn
  - preprocessing
    - oridinalEncoder
      - fit_transform

In [30]:
visa_df=pd.read_csv(r'C:\Users\HP\Documents\Data_File\Visadataset.csv')
visa_df['education_of_employee'].unique()
order=[['High School', "Master's", "Bachelor's", 'Doctorate']]

In [34]:

from sklearn.preprocessing import OrdinalEncoder
Oe=OrdinalEncoder(categories=order)
Oe.fit_transform(visa_df[['education_of_employee']])

array([[0.],
       [1.],
       [2.],
       ...,
       [1.],
       [1.],
       [2.]], shape=(25480, 1))

**One Hot Encoder**
- One hot means at a time only one value **ON**
  
- Other will be ***OFF**

- ON means one value become **True**

- OFF means one values beacome **False**

- True means one value become **1**

- False means one value become **0**

- first we need to know how many unique labels are there

- for ex:-**case_status** has two unique labels

     - Certified
     - Denied
- so one hot encoder creates two new columns

     - case_status_certified
     - case_status_denied

| Case_Status | Certified | Denied |
|-------------|-----------|--------|
| Certified   |    1      |   0    |
| Denied      |    0      |   1    |
| Certified   |    1      |   0    |
| Denied      |    0      |   1    |

 |Case_Status|Certified|Denied|

**pd.get_dummies**

- pd.get_dummies() is a Pandas function used for one-hot encoding
                                             
- converting categorical data into numerical columns.
- Machine learning models can`t understand text like:
     - Certified, Denied
- So we convert it into numbers.

In [48]:
visa_df['continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [49]:
pd.get_dummies(visa_df['continent'])

       Africa   Asia  Europe  North America  Oceania  South America
0       False   True   False          False    False          False
1       False   True   False          False    False          False
2       False   True   False          False    False          False
3       False   True   False          False    False          False
4        True  False   False          False    False          False
...       ...    ...     ...            ...      ...            ...
25475   False   True   False          False    False          False
25476   False   True   False          False    False          False
25477   False   True   False          False    False          False
25478   False   True   False          False    False          False
25479   False   True   False          False    False          False

[25480 rows x 6 columns]

In [50]:
visa_df_encoder=pd.get_dummies(visa_df['continent'])

In [51]:
visa_df_encoder

       Africa   Asia  Europe  North America  Oceania  South America
0       False   True   False          False    False          False
1       False   True   False          False    False          False
2       False   True   False          False    False          False
3       False   True   False          False    False          False
4        True  False   False          False    False          False
...       ...    ...     ...            ...      ...            ...
25475   False   True   False          False    False          False
25476   False   True   False          False    False          False
25477   False   True   False          False    False          False
25478   False   True   False          False    False          False
25479   False   True   False          False    False          False

[25480 rows x 6 columns]

In [53]:
visa_df_encoder=pd.get_dummies(visa_df['continent']).astype(int)

In [54]:
visa_df_encoder

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [64]:
for i in cat[1:]:
    visa_df_encoder=pd.get_dummies(visa_df,columns=cat[1:],dtype=int)

In [65]:

visa_df_encoder

,case_id,no_of_employees,yr_of_estab,prevailing_wage,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_0,case_status_1
0,EZYV01,14513,2007,592.2029,0,1,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,EZYV02,2412,2002,83425.6500,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,EZYV03,44444,2008,122996.8600,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,EZYV04,98,1897,83434.0300,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,EZYV05,1082,2005,149907.3900,1,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,2601,2008,77092.5700,0,1,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,EZYV25477,3274,2006,279174.7900,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,EZYV25478,1121,1910,146298.8500,0,1,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,EZYV25479,1918,1887,86154.7700,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,EZYV25480,3195,1960,70876.9100,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

In [63]:
visa_df_encoder

       0  1
0      0  1
1      1  0
2      0  1
3      0  1
4      1  0
...   .. ..
25475  1  0
25476  1  0
25477  1  0
25478  1  0
25479  1  0

[25480 rows x 2 columns]

In [68]:


for i in cat[1:]:
    dummies = pd.get_dummies(visa_df[i], prefix=i, dtype=int)
    encoded_df = pd.concat([encoded_df, dummies], axis=1)
# prefix:- avoid duplicate column names
# dtype=int:- ensure output is 1and 0
# axis:- give the direction

In [69]:
encoded_df

,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,education_of_employee_Bachelor's,education_of_employee_Doctorate,education_of_employee_High School,education_of_employee_Master's,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_0,case_status_1
0,0,1,0,0,0,0,0,0,1,0,...,0,1,1,0,0,0,0,1,0,1
1,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,1,0
2,0,1,0,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,0,1,0,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,1,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,0,1,0,0,0,0,1,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,1,1,0
25477,0,1,0,0,0,0,0,0,0,1,...,1,0,0,0,0,1,1,0,1,0
25478,0,1,0,0,0,0,0,0,0,1,...,0,1,0,0,0,1,0,1,1,0
25479,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,1,0

**Binary Encoding**
- convert cat into num numbers and split into columns
- Useful for high-cardinality data

In [2]:
# import library
import pandas as pd
import category_encoders as ce
# call dataset
visa_df=pd.read_csv(r'C:\Users\HP\Documents\Data_File\Visadataset.csv')
# cat column
cat=visa_df.select_dtypes(include='object').columns
# apply binary encoding
encoder=ce.BinaryEncoder(cols=cat_cols)
visa_df_encoded=encoder.fit_transformer(visa_df)
visa_df_encoded

ModuleNotFoundError: No module named 'category_encoders'

In [3]:
import pandas as pd
import category_encoders as ce

ModuleNotFoundError: No module named 'category_encoders'