**Import**

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
np.__version__

'2.4.2'

**Rdataead the data**
- visa data
- Bank data

In [16]:
pd.read_csv(r'C:\Users\HP\Documents\Data_File\Visadataset.csv')

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [17]:
visa_df=pd.read_csv(r'C:\Users\HP\Documents\Data_File\Visadataset.csv')

In [27]:
# viewing the data
visa_df.head()
visa_df.tail()
visa_df.sample()
visa_df.shape
visa_df.columns
visa_df.index
visa_df.values
#Data information
visa_df.info()
visa_df.describe()
visa_df.describe(include='all')
visa_df.dtypes
# Selection and indexing
visa_df.loc[]
visa_df.iloc[]

visa_df.at[]
visa_df.iat[]
#Aggregation Functions
visa_df.sum()
visa_df.mean()
visa_df.median()
visa_df.min()
visa_df.max()
visa_df.std()
visa_df.count()
#Missing Values
visa_df.isnull()
visa_df.notnull()
visa_df.dropna()
visa_df.fillna()

SyntaxError: invalid syntax (1391794507.py, line 15)

In [28]:
visa_df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [29]:
visa_df.tail()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [30]:
visa_df.shape

(25480, 12)

In [31]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [32]:
visa_df.index

RangeIndex(start=0, stop=25480, step=1)

In [33]:
visa_df.values

array([['EZYV01', 'Asia', 'High School', ..., 'Hour', 'Y', 'Denied'],
       ['EZYV02', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV03', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Denied'],
       ...,
       ['EZYV25478', 'Asia', "Master's", ..., 'Year', 'N', 'Certified'],
       ['EZYV25479', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV25480', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Certified']],
      shape=(25480, 12), dtype=object)

In [34]:
visa_df.isnull()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,False,False,False,False,False,False,False,False,False,False,False,False
25476,False,False,False,False,False,False,False,False,False,False,False,False
25477,False,False,False,False,False,False,False,False,False,False,False,False
25478,False,False,False,False,False,False,False,False,False,False,False,False
25479,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
visa_df.dtypes() # not callable

TypeError: 'Series' object is not callable

In [9]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [10]:
data_types=visa_df.dtypes
type(data_types)

pandas.core.series.Series

In [11]:
type(visa_df)

pandas.core.frame.DataFrame

**series**
- series is a ky value pair
- series kind of a dictionary

In [12]:
data_types.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [13]:
data_types.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [14]:
data_types.index

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [15]:
data_types.keys()
data_types.values
##################################
data_types.index
data_types.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

- when we have a series
- we need to make to separate lists
- so that we can able to create a dataframe

In [18]:
visa_df #df
visa_df.dtypes # type series
keys=visa_df.dtypes.keys() # keys
values=visa_df.dtypes.values # values
df1=pd.DataFrame(zip(keys,values),
                columns=['Visa data','Data type'])
df1

                Visa data Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

**task**
- separate cat and num column in different list
- using dtypes

In [18]:
# idea
# extreact keys and values
# apply the for loop
# check the condition if the data type= odject then
# append in cat list
# otherwise append in num list
keys=visa_df.dtypes.keys() 
values=visa_df.dtypes.values
cat,num=[],[]
for i,j in zip(keys,values):
    print(i,j)
    if j=='object':
        cat.append(i)
    else:
        cat.append(i)

case_id object
continent object
education_of_employee object
has_job_experience object
requires_job_training object
no_of_employees int64
yr_of_estab int64
region_of_employment object
prevailing_wage float64
unit_of_wage object
full_time_position object
case_status object

In [ ]:
visa_df.iloc[100:105,3:7] #df
visa_df.iloc[100] #s
visa_df.iloc[[100]] #df
visa_df.iloc[[100,200,300],]#df
visa_df.iloc[[100,200,300],:] #df
visa_df.iloc[:,[3,6,9]] #df
visa_df.iloc[:,3] #s
visa_df.iloc[:,[3]] #df
visa_df.iloc[:,:] #d

In [19]:
visa_df.iloc[100:105,3:7]

    has_job_experience requires_job_training  no_of_employees  yr_of_estab
100                  Y                     N             2227         2007
101                  Y                     N              334         2007
102                  Y                     N              224         2008
103                  Y                     N              367         1982
104                  Y                     N              306         2003

In [20]:
visa_df.iloc[100]

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [26]:
visa_df.iloc[[100,200,300],:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [27]:
visa_df.iloc[:,3]

0        N
1        Y
2        N
3        N
4        Y
        ..
25475    Y
25476    Y
25477    Y
25478    Y
25479    Y
Name: has_job_experience, Length: 25480, dtype: object

In [29]:
visa_df.loc[:,]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

- Bank Data

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
pd.read_csv(r"C:\Users\HP\Documents\Data_File\bank.csv",sep=';')

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [22]:
bank_df=pd.read_csv(r"C:\Users\HP\Documents\Data_File\bank.csv",sep=';')

In [23]:
bank_df.head(3)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no

In [24]:
bank_df.tail()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [25]:
bank_df.tail(2)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [26]:
bank_df.shape

(4521, 17)

In [27]:
bank_df.size

76857

In [28]:
bank_df.isnull()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4517,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4518,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4519,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4520,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [29]:
bank_df.dtypes()

TypeError: 'Series' object is not callable

In [30]:
bank_df.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [31]:
data_types=bank_df.dtypes
type(data_types)

pandas.core.series.Series

In [32]:
type(bank_df)

pandas.core.frame.DataFrame

In [34]:
bank_df #df
bank_df.dtypes # type series
keys=bank_df.dtypes.keys() # keys
values=bank_df.dtypes.values # values
df1=pd.DataFrame(zip(keys,values),
                columns=['Bank data','Data type'])
df1

    Bank data Data type
0         age     int64
1         job    object
2     marital    object
3   education    object
4     default    object
5     balance     int64
6     housing    object
7        loan    object
8     contact    object
9         day     int64
10      month    object
11   duration     int64
12   campaign     int64
13      pdays     int64
14   previous     int64
15   poutcome    object
16          y    object